package customOrders;
import customOrders.Customer;

import java.sql.*;
import java.util.ArrayList;
import java.util.List;

public class CustomerManager {

    /**
     * Busca un cliente en la base de datos por su email.
     *
     * @param email The email to search for.
     * @return The Customer object if found, or null if it doesn't exist.
     */
    public Customer getCustomerByEmail(String email) throws SQLException {
        String sql = "SELECT Customer_ID, First_Name, Last_Name, Email, Phone_Number, Address FROM Customers WHERE Email = ?";
        Customer customer = null;

        try (Connection conn = PostgresConnector.getConnection();
             PreparedStatement ps = conn.prepareStatement(sql)) {

            ps.setString(1, email);

            try (ResultSet rs = ps.executeQuery()) {
                if (rs.next()) {
                    customer = new Customer(
                            rs.getInt("Customer_ID"),
                            rs.getString("First_Name"),
                            rs.getString("Last_Name"),
                            rs.getString("Email"),
                            rs.getString("Phone_Number"),
                            rs.getString("Address")
                    );
                }
            }
        }
        return customer;
    }

    /**
     * Inserta un nuevo cliente en la base de datos.
     * @param customer The Customer object with registration data.
     * @return The ID generated by the database, or -1 if it fails.
     */
    public int insertCustomer(Customer customer) throws SQLException {
        // Use CURRENT_DATE in PostgreSQL for the join date
        String sql = "INSERT INTO Customers (First_Name, Last_Name, Email, Phone_Number, Date_Joined, Address) VALUES (?, ?, ?, ?, CURRENT_DATE, ?)";
        int generatedId = -1;

        try (Connection conn = PostgresConnector.getConnection();
             PreparedStatement ps = conn.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {

            ps.setString(1, customer.getFirstName());
            ps.setString(2, customer.getLastName());
            ps.setString(3, customer.getEmail());
            ps.setString(4, customer.getPhoneNumber());
            ps.setString(5, customer.getAddress());

            ps.executeUpdate();
            try (ResultSet rs = ps.getGeneratedKeys()) {
                if (rs.next()) generatedId = rs.getInt(1);
            }
        }
        return generatedId;
    }

    /**
     * Gets all customers (mainly used by the Admin Dashboard).
     */
    public List<Customer> getAllCustomers() throws SQLException {
        List<Customer> customerList = new ArrayList<>();
        String sql = "SELECT Customer_ID, First_Name, Last_Name, Email, Phone_Number, Address FROM Customers ORDER BY Customer_ID";

        try (Connection conn = PostgresConnector.getConnection();             PreparedStatement ps = conn.prepareStatement(sql);
             ResultSet rs = ps.executeQuery()) {

            while (rs.next()) {
                Customer customer = new Customer(
                        rs.getInt("Customer_ID"),
                        rs.getString("First_Name"),
                        rs.getString("Last_Name"),
                        rs.getString("Email"),
                        rs.getString("Phone_Number"),
                        rs.getString("Address")
                );
                customerList.add(customer);
            }
        }
        return customerList;
    }

    /**
     * Updates the data of an existing customer.
     */
    public boolean updateCustomer(Customer customer) throws SQLException {
        String sql = "UPDATE Customers SET First_Name = ?, Last_Name = ?, Email = ?, Phone_Number = ?, Address = ? WHERE Customer_ID = ?";

        try (Connection conn = PostgresConnector.getConnection();
             PreparedStatement ps = conn.prepareStatement(sql)) {

            ps.setString(1, customer.getFirstName());
            ps.setString(2, customer.getLastName());
            ps.setString(3, customer.getEmail());
            ps.setString(4, customer.getPhoneNumber());
            ps.setString(5, customer.getAddress());
            ps.setInt(6, customer.getCustomerID());

            return ps.executeUpdate() > 0;
        }
    }

    /**
     * Deletes a customer by their ID.
     */
    public boolean deleteCustomer(int customerId) throws SQLException {
        String sql = "DELETE FROM Customers WHERE Customer_ID = ?";

        try (Connection conn = PostgresConnector.getConnection();
             PreparedStatement ps = conn.prepareStatement(sql)) {

            ps.setInt(1, customerId);
            return ps.executeUpdate() > 0;
        }
    }
}